#pragma once
#include <string>
#include <unordered_map>
#include <vector>
#include <memory>
#include <iostream>
#include <nlohmann/json.hpp>
#include <thread>
#include <lodepng.h>
#include <sstream>
#include <queue>
#include <mutex>
#include <Windows.h>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <wrl.h>
#include <locale>
#include <codecvt>
#include <condition_variable>
#include <engine.h>