#pragma once
#include "log.h"
#include <string>
#include <unordered_map>
#include <vector>
#include <memory>
#include <iostream>
#include <nlohmann/json.hpp>
#include <thread>
#include <lodepng.h>
#include <sstream>
#include <queue>
#include <mutex>
#include <Windows.h>
#include <spdlog/spdlog.h>
#include <spdlog/sinks/stdout_color_sinks.h>
#include <wrl.h>
#include "common.h"
#include <locale>
#include <codecvt>
#include <d3d12.h>
#include <D3Dcompiler.h>
#include "transform.h"
#include <condition_variable>